name: backend_vania
description: My First Backend Development
version: 1.0.0

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.6
  dart_jsonwebtoken: ^2.14.2
  dio: ^5.8.0+1
  vania: ^0.8.2+1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.9

dependency_overrides:
  pointycastle: 4.0.0
